name: python-38

on:
  push:
    branches:
      - master
  schedule:
    - cron: "38 * * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      LOCALE: zh_CN
      VERSION: "3.8"
    steps:
      - uses: actions/checkout@v3
      - name: prepare
        run: .github/scripts/prepare.sh
      - name: update
        run: .github/scripts/update.sh
        env:
          TRANSIFEX_APIKEY: ${{ secrets.TRANSIFEX_APIKEY }}
      - name: build
        run: .github/scripts/build.sh
      - name: commit
        run: .github/scripts/commit.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
